### ISSUE TITLE
About Training Time

### ISSUE THREAD

**Issue by AmingWu** [aminebdj/OpenYOLO3D#1]
Dear Authors,

How long does your method need to train?

Thanks

**Comment by aminebdj** [comment]
Dear @AmingWu,

Thanks a lot for your interest in our work,

Our model is training free, we use pre-trained Mask3D for class agnostic mask generation, and YoloWorld for mask prompting with text.

Many thanks,
Mohamed

**Comment by aminebdj** [comment]
Dear @AmingWu, I am going to close this issue.

Thanks,
