### ISSUE TITLE
Scaling bounding box of 3D instances for IoU calculation

### ISSUE THREAD

**Issue by shjung13** [aminebdj/OpenYOLO3D#10]
Hello Authors,

Thank you for the great work!

We are running and visualizing your code and it seems like the bounding boxes of 2D projection of each instance have to be scaled back again using `scaling_params`. 

Line: https://github.com/aminebdj/OpenYOLO3D/blob/1a01f09cfdd5efe356bf48ece991b5dd7aa12589/utils/__init__.py#L197

When we visualize the bboxes, after scaling this, i.e., `x_l /= scaling_params[1]`, I can see their bounding boxes are aligned to the images correctly.

I know this may not affect to selected labels since label map is already scaled, but this seems to affect to normalization.

Would you let me know this finding is correct?

Thanks.

Best,
Sanghun

**Comment by aminebdj** [comment]
Dear @shjung13,

Yes, you are correct, and thanks for letting me know; the bounding box from the projection should be scaled back.

Best,

**Comment by shjung13** [comment]
Thank you for the confirmation. I will close this issue.
