### ISSUE TITLE
About the "topk_per_image" in "config_scannet200.yaml"

### ISSUE THREAD

**Issue by cjm-jamie** [aminebdj/OpenYOLO3D#11]
Dear authors,

Thank you for your awesome work and for releasing the code.

I found that at the `pretrained/config_scannet200.yaml`, the `topk_per_image` is set to 600 as default (which I can't find the detail or ablation study in your arxiv paper as far as I know, code implementation is in `utils/__init__.py`, from `line243` to `line260`), is that the default setting to reproduce your work to get the final result as you listed on your paper?

If yes, I'm wondering how you get the final segmentation result (mask label per point) from this top600 mask-label pair? Is that similar to the `save_output_as_ply` function in `utils/__init__.py` ? Or how you get the final result as you listed on your paper?

Thank you very much!

**Comment by aminebdj** [comment]
Dear @cjm-jamie,

Thanks for your interest in our work, and sorry for the delay,

The top-k is just used for post-processing and is not part of the main method. It was adopted by state-of-the-art [Open3DIS](https://github.com/VinAIResearch/Open3DIS), which proved to boost performance. The setting in the config file we provide should give you the exact numbers we report in our arxiv. While `save_output_as_ply ` is to visualize the predicted instances corresponding to the text prompts following [line 8](https://github.com/aminebdj/OpenYOLO3D/blob/a75f0716506724c3f60b4aaa3e1d93afb5a458e3/single_scene_inference.py#L8).

**Comment by cjm-jamie** [comment]
@aminebdj Thank you very much for your detailed response and for clarifying the purpose of the top-k setting and the function of save_output_as_ply. I appreciate your time and effort in explaining this.

I will proceed to close this issue now. Thanks again for your excellent work!
