### ISSUE TITLE
What is the meaning of the ground truth .txt file?

### ISSUE THREAD

**Issue by Yenhongxuan** [aminebdj/OpenYOLO3D#13]
![截圖 2024-09-09 晚上10 47 55](https://github.com/user-attachments/assets/7c541130-536f-4298-a5ae-adec0d0db523)
Can you explain what the ground truth .txt file represents? Does it represent the corresponding semantic label? If yes, can you provide the corresponding list?

Thanks.

**Comment by aminebdj** [comment]
Dear @Yenhongxuan,

Thank you for your interest in our work,

Yes, it represents instance and semantic ground truth as per Mask3D preprocessing. The files are already shared. Please run `sh get_replica_dataset.sh` to download and unpack it. 

Please let me know if you find any more issues, 

Best,
Mohamed
