### ISSUE TITLE
How to get scannet200's intrinsics.txt

### ISSUE THREAD

**Issue by spatiall** [aminebdj/OpenYOLO3D#14]
Hello author, regarding the scannet200 data, I see that each scene in the structure you gave contains an intrinsics.txt. Using the preprocessing code provided in ScanNet, I extracted the color, depth, pose, and intrinsics information of each scene, but for each scene, what I got was the intrinsics directory, which contains intrinsic_depth.txt, intrinsic_color.txt, extrinsic_depth .txt, extrinsic_color.txt four files. I would like to ask how to convert the obtained data into the intrinsics.txt you mentioned, or is there any other way to generate the intrinsics.txt file?
Thanks for your answer!

**Comment by flyintr** [comment]
Hello, is the preprocessing code provided in the email of ScanNet 200 datatset?
