### ISSUE TITLE
Text-guided promptable segmentation

### ISSUE THREAD

**Issue by Yebulabula** [aminebdj/OpenYOLO3D#2]
Dear authors,

Thanks for your fantastic work. It is very beneficial to the community of the 3D OV segmentation research field. May I ask if OpenYOLO3D enables segmentation with text prompts similar to SAM in 2D?

Thanks.

Best wishes,
Ye

**Comment by aminebdj** [comment]
Dear @Yebulabula,

Thanks a lot for your interest in our work,

Yes it is possible to prompt our model with text similar to 2D SAM, we will share the checkpoints for single 3D scene inference and data for evaluation in few days, so please keep an eye on the repository.

Many thanks,
Mohamed

**Comment by aminebdj** [comment]
Dear @Yebulabula,

I updated the repo for single-scene inference,

You can infer from your 3D scene, which has to be structured similarly to the Replica sample in [Data preparation](https://github.com/aminebdj/OpenYOLO3D/edit/main/docs/Data_prep.md), you can change the text prompt in [confg.yaml file line 9](https://github.com/aminebdj/OpenYOLO3D/blob/86a9b2a547e89c2f4a56df0e5ead22fbde88a0d7/pretrained/config.yaml#L9) and run the following single scene inference [code](https://github.com/aminebdj/OpenYOLO3D/blob/86a9b2a547e89c2f4a56df0e5ead22fbde88a0d7/README.md#L86)

Best,
Mohamed

**Comment by Yebulabula** [comment]
Dear Mohamed,

Thanks for your response. It is very helpful, may I ask if your method leverage both 2D and 3D sgementator for promptable segmentation or only using 2D ones?

Thanks.

Best wishes,
Ye

**Comment by aminebdj** [comment]
Hello @Yebulabula,

Our model uses only a 3D segmentor to extract 3D class agnostic instance masks. While the 2D open vocabulary object detector (yoloworld) is only used to prompt the class agnostic masks.

Best,
Mohamed

**Comment by Yebulabula** [comment]
Hi Mohamed,

Thanks. I get it. I will close this issue. Your explanation is very clear.

Best,
Ye
