### ISSUE TITLE
Code for visualizations

### ISSUE THREAD

**Issue by shjung13** [aminebdj/OpenYOLO3D#5]
Hi authors,

Thank you for releasing the code for this great work!

I was able to successfully reproduce the performance in the paper.

But, I still wonder if there is any way that I can visualize the results.

Do you have any plan to release codes for visualizations?

or Would you give me a sample script / code that I can develop on for the visualizations?

Please feel free to contact through my email if you prefer email over github issue for sharing the code!

Email: shjung13 [at] cs.washington.edu

Thank you!

Best,
Sanghun

**Comment by aminebdj** [comment]
dear @shjung13,

Thank you for your interest in our work,

I updated the repository, so please pull it again. If you already downloaded the replica dataset we provided you can use one of the sample point clouds there, I provided a sample code. For visualization, you can use pyviz3d you can install it with the following command `python -m pip install pyviz3d`/

```
from utils import OpenYolo3D
import os
import pyviz3d.visualizer as viz

openyolo3d = OpenYolo3D(f"{os.getcwd()}/pretrained/config.yaml")
prediction = openyolo3d.predict(path_2_scene_data=f"{os.getcwd()}/data/replica/office0", depth_scale=6553.5, text = ["chair"]) 
openyolo3d.save_output_as_ply(f"{os.getcwd()}/output.ply", True) 
v.add_mesh('Room', path='f"{os.getcwd()}/output.ply"')
for i in range(3):
        ii = i / 3.0
        pos_x = np.cos(ii) * 2.0
        pos_y = np.sin(ii) * 2.0
        v.add_mesh('Chairs;'+str(i),
                   path='examples/data/chair_model.obj',
                   color=np.array([255, i * 30, 0]),
                   translation=np.array([pos_x, pos_y, -1.0]),
                   rotation=viz.euler_to_quaternion(np.pi / 2.0, 0.0, np.pi / 4.0 * i))

    blender_args = {'output_prefix': './',
                    'executable_path': '/Applications/Blender.app/Contents/MacOS/Blender'}
    v.save('example_meshes', blender_args=blender_args)
```

**Comment by shjung13** [comment]
Thank you so much for the quick reply! I can see them correctly :)
