### ISSUE TITLE
Missing 'num_classes Parameter in Config Files for ScanNet200 and Replica Datasets

### ISSUE THREAD

**Issue by Jxy04250** [aminebdj/OpenYOLO3D#7]
Hi,

Thank you so much for this great work! However, when I try to run the code, I noticed that the 'num_classes' parameter is missing in the config files for both the ScanNet200 and Replica datasets. This causes an error at line 256 in utils/__init__.py. Could you please let me know what values I should set for 'num_classes' for these datasets?

Thank you very much!

**Comment by aminebdj** [comment]
Dear @Jxy04250,

Thanks for pointing this out; I updated the repo, and it should work with no issue now.

Thanks

**Comment by Jxy04250** [comment]
Dear @aminebdj,

Thank you so much for your prompt reply.

Warm regards,
Xueying
