### ISSUE TITLE
Challenges in Reproducing ScanNet200 Results

### ISSUE THREAD

**Issue by Jxy04250** [aminebdj/OpenYOLO3D#9]
Dear @aminebdj ,

Thank you again for your outstanding work! I have followed the instructions to reproduce the results. However, I encountered significant discrepancies when trying to reproduce the results for ScanNet200 using both precomputed masks and oracle 3D masks. The results I obtained are quite different from those reported in the paper. I have attached the results for both cases.

Could you please provide any insights or guidance on how to accurately reproduce the results?

Thank you very much!

Results of ScanNet200 with precomputed-masks:
![results of ScanNet200 with precomputed-masks](https://github.com/user-attachments/assets/e305ce9a-a887-4add-b3e1-6373dc0b9a80)

Results of ScanNet200 with oracle 3D masks:
![results of ScanNet200 with oracle 3D masks](https://github.com/user-attachments/assets/2aab03fb-11cc-452a-92bd-28cf49e54995)

**Comment by aminebdj** [comment]
Hey @Jxy04250,

Thanks for sharing,

Could you please share the details on the scannet200 dataset you are using?

The one I am using is with the original image and depth size:
Image resolution: 1296x968
Depth map resolution: 640x480

thanks

**Comment by Jxy04250** [comment]
Hi @aminebdj ,

The image resolution and depth map resolution I used are the same as yours. And the other details I used are also the same as yours.
Actually, I kept the original configuration download from your Github repo without any change.

My guess is the processing of Scannet makes ours different.

Could you please send me the ScanNet200 datasets you are using? 

I'll follow the rules required by the official ScanNet200 dataset, and will not bring any potential law issue to you.

Thank you so much!

**Comment by aminebdj** [comment]
Hey @Jxy04250,

As long as you followed [Mask3D preprocessing](https://github.com/JonasSchult/Mask3D), the ground truth masks should be the same as mine. I will email the pre-processed dataset shortly; please keep me updated if that solves the issue.

best

**Comment by aminebdj** [comment]
This [scene0011_00.txt](https://github.com/user-attachments/files/16403843/scene0011_00.txt) is the ground truth file for the `scene0011_00` sample, it would be good if you could check whether it is similar to yours or not.

**Comment by Jxy04250** [comment]
Hi @aminebdj 

I have compared the two `scene0011_00.txt` of yours and mine. They are quite different. 
By the way, I also checked the pipeline of processing the dataset, showing that I have followed the Mask3D preprocessing.

Could you please share me with all the processed files for the ScanNet200 dataset? My email address is xueying003@e.ntu.edu.sg

I haven't tried the Replica dataset. I will update with you once I have tried.

Thank you and best regards.

**Comment by Jxy04250** [comment]
Dear @,

Thank you once again for your help. I ran the experiments using the preprocessed Scannet200 dataset you provided, and the performance perfectly aligns with the results reported in Table 1 of your paper. It appears that the issue lies with my data processing.
Thank you very much!

**Comment by Jxy04250** [comment]
Dear @aminebdj,

Thank you once again for your help. I ran the experiments using the preprocessed ScanNet200 dataset you provided, and the performance perfectly aligns with the results reported in Table 1 of your paper. It appears that the issue lies with my data processing.

Thank you very much!

**Comment by cjm-jamie** [comment]
Hi @aminebdj

I've met the same problem reproducing Scannet200, could you please also kindly share me with all the processed files (especially the ground truth .txt file) for the ScanNet200 dataset? My email address is cjm108061535@gapp.nthu.edu.tw

Thank you very much!

**Comment by aminebdj** [comment]
Hello @Jxy04250,

I will share the pre-processed scannet and scannet200 data soon on the GitHub repo; you will also be requested to sign and send the terms of use of scannet200 data to the scannet200 authors before downloading the preprocessed data. 

Thanks a lot.

**Comment by Jxy04250** [comment]
Hi @aminebdj,

Noted, and thank you for the reminder! I’ll make sure to follow the necessary steps before downloading the preprocessed data.

Thanks again!
